#include <ddk/ntddk.h>

#define MY_IOCTL_DIRECT_IN_IO \
		CTL_CODE(FILE_DEVICE_UNKNOWN, \
				0x800, \
				METHOD_IN_DIRECT, \
				FILE_READ_DATA | FILE_WRITE_DATA)

#define MY_IOCTL_DIRECT_OUT_IO \
		CTL_CODE(FILE_DEVICE_UNKNOWN, \
				0x801, \
				METHOD_OUT_DIRECT, \
				FILE_READ_DATA | FILE_WRITE_DATA)

#define MY_IOCTL_BUFFERED_IO \
		CTL_CODE(FILE_DEVICE_UNKNOWN, \
				0x802, \
				METHOD_BUFFERED, \
				FILE_READ_DATA | FILE_WRITE_DATA)
