#include "ar_reader.h"

#include <cfgmap.h>

void init_map() {
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_UNKNOWN	, "Machine unknown");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_AM33		, "Machine i386");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_AMD64	, "Machine amd64");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_ARM		, "Machine arm");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_EBC		, "Machine ebc");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_I386		, "Machine i386");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_IA64		, "Machine ia64");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_M32R		, "Machine m32r");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_MIPS16	, "Machine mips16");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_MIPSFPU	, "Machine mipsfpu");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_MIPSFPU16, "Machine mipsfpu16");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_POWERPC	, "Machine powerpc");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_POWERPCFP, "Machine powerpcfp");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_R4000	, "Machine r4000");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_SH3		, "Machine sh3");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_SH3DSP	, "Machine sh3dsp");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_SH4		, "Machine sh4");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_SH5		, "Machine sh5");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_THUMB	, "Machine thumb");
	set_record(SECTION_MACHINE, IMAGE_FILE_MACHINE_WCEMIPSV2, "Machine wcemipsv2");
	
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_RELOCS_STRIPPED			, "Relocations stripped");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_EXECUTABLE_IMAGE			, "Executable image");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_LINE_NUMS_STRIPPED		, "Line numbers stripped (deprecated)");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_LOCAL_SYMS_STRIPPED		, "Local symbols stripped (deprecated)");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_AGGRESIVE_WS_TRIM 		, "Agressive working set trim (obsolete)");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_LARGE_ADDRESS_AWARE		, "Can handle large addresses");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_BYTES_REVERSED_LO		, "Little endian (deprecated)");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_32BIT_MACHINE			, "32bit");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_DEBUG_STRIPPED			, "Debug info stripped");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP	, "Can run from SWAP - Removable media");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_NET_RUN_FROM_SWAP		, "Can run from SWAP - Network");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_SYSTEM					, "System file");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_DLL						, "DLL");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_UP_SYSTEM_ONLY			, "Only uniprocessor machine");
	set_record(SECTION_CHARACTERISTICS, IMAGE_FILE_BYTES_REVERSED_HI		, "Big endian (deprecated)");
	
	set_record(SECTION_IMPORT_HEADER, IMPORT_CODE		, "Executable code");
	set_record(SECTION_IMPORT_HEADER, IMPORT_DATA		, "Data");
	set_record(SECTION_IMPORT_HEADER, IMPORT_CONST		, "Specified as CONST in the .def file");
	
	set_record(SECTION_IMPORT_NAME_HEADER, IMPORT_ORDINAL			, "IMPORT_ORDINAL");
	set_record(SECTION_IMPORT_NAME_HEADER, IMPORT_NAME				, "IMPORT_NAME");
	set_record(SECTION_IMPORT_NAME_HEADER, IMPORT_NAME_NOPREFIX		, "IMPORT_NAME_NOPREFIX");
	set_record(SECTION_IMPORT_NAME_HEADER, IMPORT_NAME_UNDECORATE	, "IMPORT_NAME_UNDECORATE");
	
	set_record(SECTION_SECTION_NUMBER_VALUE, IMAGE_SYM_UNDEFINED, "IMAGE_SYM_UNDEFINED");
	set_record(SECTION_SECTION_NUMBER_VALUE, IMAGE_SYM_ABSOLUTE	, "IMAGE_SYM_ABSOLUTE");
	set_record(SECTION_SECTION_NUMBER_VALUE, IMAGE_SYM_DEBUG	, "IMAGE_SYM_DEBUG");
	
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_END_OF_FUNCTION	, "IMAGE_SYM_CLASS_END_OF_FUNCTION");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_NULL				, "IMAGE_SYM_CLASS_NULL");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_AUTOMATIC			, "IMAGE_SYM_CLASS_AUTOMATIC");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_EXTERNAL			, "IMAGE_SYM_CLASS_EXTERNAL");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_STATIC			, "IMAGE_SYM_CLASS_STATIC");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_REGISTER			, "IMAGE_SYM_CLASS_REGISTER");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_EXTERNAL_DEF		, "IMAGE_SYM_CLASS_EXTERNAL_DEF");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_LABEL				, "IMAGE_SYM_CLASS_LABEL");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_UNDEFINED_LABEL	, "IMAGE_SYM_CLASS_UNDEFINED_LABEL");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_MEMBER_OF_STRUCT	, "IMAGE_SYM_CLASS_MEMBER_OF_STRUCT");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_ARGUMENT			, "IMAGE_SYM_CLASS_ARGUMENT");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_STRUCT_TAG		, "IMAGE_SYM_CLASS_STRUCT_TAG");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_MEMBER_OF_UNION	, "IMAGE_SYM_CLASS_MEMBER_OF_UNION");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_UNION_TAG			, "IMAGE_SYM_CLASS_UNION_TAG");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_TYPE_DEFINITION	, "IMAGE_SYM_CLASS_TYPE_DEFINITION");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_UNDEFINED_STATIC	, "IMAGE_SYM_CLASS_UNDEFINED_STATIC");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_ENUM_TAG			, "IMAGE_SYM_CLASS_ENUM_TAG");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_MEMBER_OF_ENUM	, "IMAGE_SYM_CLASS_MEMBER_OF_ENUM");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_REGISTER_PARAM	, "IMAGE_SYM_CLASS_REGISTER_PARAM");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_BIT_FIELD			, "IMAGE_SYM_CLASS_BIT_FIELD");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_FAR_EXTERNAL		, "IMAGE_SYM_CLASS_FAR_EXTERNAL");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_BLOCK				, "IMAGE_SYM_CLASS_BLOCK");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_FUNCTION			, "IMAGE_SYM_CLASS_FUNCTION");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_END_OF_STRUCT		, "IMAGE_SYM_CLASS_END_OF_STRUCT");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_FILE				, "IMAGE_SYM_CLASS_FILE");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_SECTION			, "IMAGE_SYM_CLASS_SECTION");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_WEAK_EXTERNAL		, "IMAGE_SYM_CLASS_WEAK_EXTERNAL");
	set_record(SECTION_STORAGE_CLASS, IMAGE_SYM_CLASS_CLR_TOKEN			, "IMAGE_SYM_CLASS_CLR_TOKEN");

//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_REG				, "Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_DSECT				, "Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_NOLOAD			, "Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_GROUP				, "Reserved for future use");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_NO_PAD			, "Not padded (obsolete)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_COPY				, "Reserved for future use");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_CNT_CODE				, "Contains executable code");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_CNT_INITIALIZED_DATA	, "Contains initialized data");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_CNT_UNINITIALIZED_DATA, "Contains uninitialized data");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_LNK_OTHER				, "Reserved for future use");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_LNK_INFO				, "Directive section (linker info)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_TYPE_OVER				, "Reserved for future use");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_LNK_REMOVE			, "Will not be part of the image");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_LNK_COMDAT			, "Contains COMDAT data");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_GPREL					, "Contains data referenced throught Global Pointer");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_FARDATA			, "Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_PURGEABLE			, "Reserved for future use");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_16BIT				, "ARM: Contains Thumb code /Others: Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_LOCKED				, "Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_PRELOAD			, "Reserved for future use");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_1BYTES			, "Align data 1-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_2BYTES			, "Align data 2-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_4BYTES			, "Align data 4-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_8BYTES			, "Align data 8-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_16BYTES			, "Align data 16-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_32BYTES			, "Align data 32-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_64BYTES			, "Align data 64-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_128BYTES		, "Align data 128-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_256BYTES		, "Align data 256-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_512BYTES		, "Align data 512-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_1024BYTES		, "Align data 1024-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_2048BYTES		, "Align data 2048-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_4096BYTES		, "Align data 4096-byte boundary (object)");
//	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_ALIGN_8192BYTES		, "Align data 8192-byte boundary (object)");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_LNK_NRELOC_OVFL		, "Contains extented relocation");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_DISCARDABLE		, "Can be discarded");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_NOT_CACHED		, "Cannot be cached");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_NOT_PAGED			, "Not pageable");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_SHARED			, "Can be shared in memory");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_EXECUTE			, "Can be executed as code");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_READ				, "Readable");
	set_record(SECTION_SECTION_CHARACTERISTICS, IMAGE_SCN_MEM_WRITE				, "Writable");

}
